### ISSUE TITLE
Unit testing?

### ISSUE THREAD

**Issue by qasim** [cobalt-uoft/cobalt#17]
We should have some form of testing as we build this out. How would one unit test an API?

**Comment by aleccool213** [comment]
- set up a mock server
- send example data to it
- assert the data coming back is correct 
- switch to django as it has a testing framework out of the box

**Comment by elliottsj** [comment]
Supertest is pretty good: https://github.com/visionmedia/supertest

Pair it with something like mocha, or (if you're brave) [ava](https://github.com/sindresorhus/ava). I've also heard that [tape](https://github.com/substack/tape) is good.

**Comment by qasim** [comment]
Let it begin!
![screen shot 2015-11-14 at 7 00 45 pm](https://cloud.githubusercontent.com/assets/3253505/11166458/0bcea318-8b02-11e5-88ab-f28c0a403085.png)

**Comment by elliottsj** [comment]
So brave :joy:

**Comment by elliottsj** [comment]
Even ava doesn't use ava :open_mouth: https://github.com/sindresorhus/ava/blob/97409864e2f2f3ed103b13ae6602cad4744a6815/test/assert.js#L2

**Comment by qasim** [comment]
Cobalt is now futuristic 🚀

I mean... how bad could this go.... time to find out 😁

**Comment by qasim** [comment]
.
