### ISSUE TITLE
Write API documentation

### ISSUE THREAD

**Issue by elliottsj** [cobalt-uoft/cobalt#2]
Need some more complete documentation on how to use the API, both for developers wishing to consume the API, and to serve as a spec for implementation.

I recommend [Apiary](http://apiary.io/).

**Comment by elliottsj** [comment]
I can make an Apiary doc to get started if you guys want :smile:

**Comment by qasim** [comment]
@elliottsj That would actually be pretty awesome! Especially the point on serving as a spec for the implementation. We're going to go over the feedback you and @arkon gave us and see if we can come up with something that sticks to RESTful principles and prove to be easier for devs.

**Comment by elliottsj** [comment]
Alright, here's something to get started: http://docs.uoftcourseapi1.apiary.io/
Repo here: https://github.com/elliottsj/uoft-course-api-blueprint

I had to make it "uoftcourseapi1" since "uoftcourseapi" was taken. Do you guys happen to own it?
Also made you guys (@qasim, @ivanzhangsolutions) editors for the Apiary doc.
