### ISSUE TITLE
Athletics API

### ISSUE THREAD

**Issue by kashav** [cobalt-uoft/cobalt#57]
Started [work](https://github.com/kshvmdn/cobalt/tree/athletics-api/src/api/athletics) on the API for athletics.

**Comment by kashav** [comment]
Running into a few problems with the dates.

Here's the Mongoose schema (no `campus` key since it isn't in the exported dataset yet)

``` js
"id": String,
"date": Date,
"events": [{
  "title": String,
  "location": String,
  "building_id": String,
  "start_time": Date,
  "end_time": Date
}]
```

So what's happening is importing the data into mongo leaves `date`, `start_time`, and `end_time` as strings rather than date types. I think it's happening cause `mongoimport` uses [strict mode representation](https://docs.mongodb.org/manual/reference/program/mongoimport/#considerations) with dates and that prevents them from being converted on import.
- http://stackoverflow.com/questions/22890082/convert-to-date-mongodb-via-mongoimport
- http://stackoverflow.com/questions/33107278/import-a-dateisodate-into-mongodb-using-mongoimport

I'm using [this](https://github.com/kshvmdn/cobalt/blob/athletics-api/src/db/index.js#L41:L50) and it's working, but it's not too clean and I imagine we'd have to do something like this for all APIs that include ISO 8601 dates/datetimes.

Let me know if there's a better fix for this or if it's fine as it is.

**Comment by qasim** [comment]
Ouch. Since we don't use BSON or whatever Mongo's extended JSON standard is, I knew we'd run in to some problem here but I hoped Mongo would just fix it for us automatically :(

That fix is fine for now, maybe mark it as a TODO and we'll revisit later.

**Comment by qasim** [comment]
Also, I'll release another version of uoft-scrapers and run the scraper to update the datasets.

**Comment by qasim** [comment]
Done!

_(P.S. go study, don't fail yer exams)_
