### ISSUE TITLE
Exams API

### ISSUE THREAD

**Issue by kashav** [cobalt-uoft/cobalt#61]
Got started on [this](https://github.com/kshvmdn/cobalt/tree/exams-api).

**Comment by kashav** [comment]
@qasim 

Need updated datasets!

**Comment by qasim** [comment]
Gave them an update. Look good?

**Comment by kashav** [comment]
They look good! Might need another one – https://github.com/cobalt-uoft/uoft-scrapers/pull/61.

Sorry! 😅

**Comment by qasim** [comment]
No worries, merged and updated 😉
