### ISSUE TITLE
Building API: keys out of order

### ISSUE THREAD

**Issue by qasim** [cobalt-uoft/cobalt#63]
Building API shows keys in different order:

<img width="330" alt="screen shot 2016-04-29 at 11 10 39 pm" src="https://cloud.githubusercontent.com/assets/3253505/14933527/9d627968-0e5f-11e6-94d4-03d29ebd6a63.png">

`polygon` should be below the `address` key.

**Comment by kashav** [comment]
Any idea why this happens? Looks like the data is ordered correctly in the database:
<img width="450" alt="screen shot 2016-05-02 at 9 11 13 pm" src="https://cloud.githubusercontent.com/assets/8116382/14972482/7895bf1c-10aa-11e6-93d6-9416bc795e85.png">

**Comment by kashav** [comment]
Also seems to happen with the Food API:

| `api/1.0/food/0446` | db |
| :-: | :-: |
| ![api](https://cloud.githubusercontent.com/assets/8116382/14972510/deda02ce-10aa-11e6-9517-9211b073ff7d.png) | ![db](https://cloud.githubusercontent.com/assets/8116382/14972540/1ed04d7a-10ab-11e6-93c3-8e34d9c16363.png) |

**Comment by qasim** [comment]
I've no clue. It used to happen when the mongoose scheme wasn't exactly the same as the scraper schema, but then it stopped. :/

**Comment by phil-bystrican** [comment]
This is an old issue but I thought I'd add that "an object is an unordered set of name/value pairs" (http://json.org/) so I don't think this represents any actual bug or issue with the code. Something might be altering the order of the keys at some point but its technically valid and the order absolutely should not be something any code relies on.

**Comment by qasim** [comment]
Good point -- we overlooked that very important detail. 😝
