### ISSUE TITLE
Campus filter not working?

### ISSUE THREAD

**Issue by Frank-K** [cobalt-uoft/cobalt#77]
https://cobalt.qas.im/api/1.0/courses/filter?q=prerequisite:%27MAT135%27&campus:%27UTSG%27

When I make the query above the second and third courses that show up have the campus as UTM.
Any reason why they are not being filtered out?

**Comment by kashav** [comment]
Our filter queries require the use of double quotes (`%22`) and can only be joined with `AND` / `OR` (not `&`), so this is actually what you're looking for:

> q=prerequisite:"MAT135" AND campus:"UTSG"

https://cobalt.qas.im/api/1.0/courses/filter?q=prerequisite:%22MAT135%22%20AND%20campus:%22UTSG%22

Our [docs](https://cobalt.qas.im/documentation/courses/filter) are quite detailed, you should give them a read if you haven't yet. Good catch on the single quote thing, we should explicitly make mention of that.
