### ISSUE TITLE
404 for cdf/labs and printers

### ISSUE THREAD

**Issue by erjin** [cobalt-uoft/cobalt#78]
I queried data with this api url https://cobalt.qas.im/api/1.0/cdf/labs?key=MY_KEY, but I got the message {"error":{"code":404,"message":"Not Found"}}. Any ideas are appreciated! Thank you!

**Comment by arkon** [comment]
I don't think @qasim has deployed the latest version of Cobalt to NPM/the hosted copy yet.

If it's absolutely necessary for you to get that data right now, you can either self-host Cobalt (using the version on the `master` branch), or fetch the data directly (see [cdf-scrapers](https://github.com/arkon/cdf-scrapers) )

**Comment by erjin** [comment]
Thank you for your reply. I self-hosted Cobalt and could get data from courses, food and etc, but I still could not get data from cdf/labs and printers.

**Comment by arkon** [comment]
Did you install cobalt-uoft from NPM?

**Comment by erjin** [comment]
Yes, I did. I can access courses data from my own url.

**Comment by qasim** [comment]
@erjin thanks for reporting!

released `0.6.0`, and deployed! updating should give you the newer APIs.

**Comment by erjin** [comment]
@qasim Thank you! I can get data for labs and printers now.
