### ISSUE TITLE
Requires database to be called cobalt

### ISSUE THREAD

**Issue by hobindar** [cobalt-uoft/cobalt#79]
Currently, the documentation seems to imply, when self-hosting, you can use whatever URI you wish for mongodb, which makes sense. However, at the moment, cobalt will fail if the URI specifies a database name other than 'cobalt'. This seems to be because 'cobalt' is hard-coded in when using mongoimport.

**Comment by hobindar** [comment]
[Possible fix.](https://github.com/hobindar/cobalt/commit/05b6107af36d156cffc850bef7719b7c373ab85a)

Edit: Or to include URIs with absent name or modified host, [possible fix](https://github.com/hobindar/cobalt/commit/4cf15d88b3cece379e7b1bcf270e58cd5f182eda). This doesn't fully support mongo URIs either. Options, for example, are ignored. This does support mongodb://host:port/name style URIs.

**Comment by kashav** [comment]
@hobindar nice catch! you can actually use `.slice(-1)` to get the last element of an array, so _this_ might a bit cleaner:

``` js
process.env.COBALT_MONGO_URI.split('/').slice(-1)
```

Thanks for the contribution!

**Comment by kashav** [comment]
Just saw the edit, I like this idea better. It looks like you can get the host/name/port through the Mongoose connection object, so you might be able to avoid having to parse the URI.

``` js
let database = mongoose.connection.name
let host = mongoose.connection.host
let port = mongoose.connection.port
```
- http://stackoverflow.com/questions/13759400/mongoose-js-get-mongo-db-name-url-from-model-instance#comment53622820_13759400
- http://stackoverflow.com/questions/23176174/mongoose-and-mongo-error-mongoose-connection-host-returns-null/23177488#23177488

**Comment by hobindar** [comment]
Were you thinking something more like [this](https://github.com/hobindar/cobalt/commit/edf99a29385942ad27f80ac7cd04d4ea66cc81c4)?

**Comment by kashav** [comment]
Yeah, that's a lot cleaner. One more thing, `mongoimport` actually has a [`--port`](https://docs.mongodb.com/manual/reference/program/mongoimport/#cmdoption--port) flag, so you don't even need to form that part yourself.

**Comment by hobindar** [comment]
I noticed the `--port` flag, but mongoimport's documentation seem to state `--host` requires the port. If you can pass just the hostname, it doesn't seem to be documented.

**Comment by hobindar** [comment]
[Here it is](https://github.com/hobindar/cobalt/commit/63525851001f3ef116d04e3af16de52eda15d876) with `--port` flag.

**Comment by kashav** [comment]
@hobindar Looks good to me. :+1: 

Submit the PR, @qasim will review when he can and merge changes.
