### ISSUE TITLE
Problem in self-hosting

### ISSUE THREAD

**Issue by erjin** [cobalt-uoft/cobalt#85]
info: Cobalt is listening at http://localhost:4242
info: Connected to MongoDB
info: Synced athletics.
info: Synced parking.
info: Synced food.
info: Synced shuttles.
info: Synced buildings.
info: Synced exams.
info: Synced textbooks.
info: Synced courses.
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

There is no labs and printers synced. Any suggestions?

**Comment by kashav** [comment]
Thanks for reporting!

https://github.com/cobalt-uoft/cobalt/pull/82 should resolve the Mongoose warning (this has been merged, but the hosted version hasn't been updated yet) and https://github.com/cobalt-uoft/cobalt/pull/83 will fix the labs & printers syncing issue.

If you need labs/printers immediately, you can clone the [`fix/cdf-urls`](https://github.com/cobalt-uoft/cobalt/tree/fix/cdf-urls) branch and build it or manually add the changes (see `path/to/project/node_modules/cobalt-uoft/lib/api/cdf/{labs,printers}/routes/list.js`).

**Comment by erjin** [comment]
Thank you! Just curious, when will you guys update the hosted version?

**Comment by kashav** [comment]
Oops, labs/printers hits a live source rather than the database, so there's nothing to sync. What's happening is expected (but the endpoints still shouldn't work, unless you've implemented the changes from #83). Sorry about that.

I'm assuming you'll see a new version in the coming days (cc @qasim).

**Comment by erjin** [comment]
Thanks a lot. I just made changes on my server. It works perfectly.

**Comment by qasim** [comment]
Thanks for reporting @erjin, a new hosted version will be released soon: there will be roughly 1 or 2 days of downtime on the hosted platform next week, after which we will be good to go again.

Sorry for the lack of responses, I don't have much bandwidth to be maintaining Cobalt as actively as I used to, which means it's probably time to hand over some responsibility to other contributors in the coming weeks to make sure the project stays healthy. In the meanwhile, thanks for using Cobalt 😇

**Comment by erjin** [comment]
Hey @qasim, is the new hosted version released? I cannot build any connections now. By the way, I think your SSL Certificates are expired. 
<img width="883" alt="screen shot 2016-10-04 at 15 40 54" src="https://cloud.githubusercontent.com/assets/6620757/19089653/46c69dee-8a49-11e6-9d9a-9db98ae0d25d.png">

**Comment by erjin** [comment]
Hey @qasim, is the new hosted version released? I cannot build any connections now. By the way, I think your SSL Certificates are expired. 
<img width="883" alt="screen shot 2016-10-04 at 15 40 54" src="https://cloud.githubusercontent.com/assets/6620757/19089674/6303d440-8a49-11e6-835f-dc1e61381bfd.png">
