### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by muradakh** [cobalt-uoft/cobalt#89]
Hi, 
It looks like there is some issue with the API. I noticed today that I get 502 responses. Everything was working a couple days ago.

Would anyone mind looking into this?

Thanks!

**Comment by isthisnagee** [comment]
Hi @MuradAkh, I've pinged @qasim and he's look into it. Thanks for bringing it up!

In the future (and for anybody else reading this), it'd be a good idea to write up steps to reproduce it.

e.g:

> It looks like there is some issue with the API. I noticed today that I get 502 responses. Everything was working a couple days ago.
>
> Trying both
>
> ```
> curl -H "Authorization: MY_API_KEY" \
> https://cobalt.qas.im/api/1.0/buildings/080
> ```
>
> and 
> 
> ```
> curl 'https://cobalt.qas.im/api/1.0/buildings/080?key=MY_API_KEY'
> ```
>
> and got as a response:
>
> ```
> <html>
> <head><title>502 Bad Gateway</title></head>
> <body bgcolor="white">
> <center><h1>502 Bad Gateway</h1></center>
> <hr><center>nginx/1.9.12</center>
> </body>
> </html>
> ```
>
> Would anyone mind looking into this?
>
> Thanks!

Anyway thanks a bunch for using Cobalt and good luck with whatever you're building 😄

**Comment by qasim** [comment]
There was an issue with cobalt trying to connect to the database server. It's since been resolved.
